function vor = vorimport(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  VOR = vorimport(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  VOR = vorimport(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  vor = vorimport("/S06,G2_/S06_G2_2019_05_24_14_41_34.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Feb-2020 14:05:13

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "RALP", "LARP", "Head", "Eye", "Eye_Vert"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
vor = readtable(filename, opts);

end