function [calibration, VORStartTime, VOREndTime] = xmlimport(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  S02G220190604123721 = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  S02G220190604123721 = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [calibration, VORStartTime] = xmlimport("VOR/S02,G2_/S02_G2_2019_06_04_12_37_21.xml", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Feb-2020 17:10:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["/", "<", ">"];

% Specify column names and types
opts.VariableNames = ["VarName1", "SystemReleaseNumber", "VarName3", "VarName4", "Var5"];
opts.SelectedVariableNames = ["VarName1", "SystemReleaseNumber", "VarName3", "VarName4"];
opts.VariableTypes = ["string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "SystemReleaseNumber", "VarName4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "SystemReleaseNumber", "VarName4", "Var5"], "EmptyFieldRule", "auto");

% Import the data
xml = readtable(filename, opts);

%% Get Calibration Values

calibration=str2double(xml.VarName3(xml.SystemReleaseNumber=="CalibrationDelta"));
VORStartTime=datetime(xml.VarName3(xml.SystemReleaseNumber=="StartDateTime"),'InputFormat','uuuu-MM-dd''T''HH:mm:ss.SSS');
VOREndTime=datetime(xml.VarName3(xml.SystemReleaseNumber=="EndDateTime"),'InputFormat','uuuu-MM-dd''T''HH:mm:ss.SSS');
end